
CREATE TABLE TB_CATEGORIA (
                ID_CATEGORIA INT AUTO_INCREMENT NOT NULL,
                NOME_CATEGORIA VARCHAR(50) NOT NULL,
                PRIMARY KEY (ID_CATEGORIA)
);


CREATE TABLE TB_PRODUTO (
                ID_PRODUTO INT AUTO_INCREMENT NOT NULL,
                NOME_PRODUTO VARCHAR(50) NOT NULL,
                DESCRICAO_PRODUTO VARCHAR(300) NOT NULL,
                PRECO_PRODUTO DOUBLE PRECISION NOT NULL,
                ID_CATEGORIA INT NOT NULL,
                PRIMARY KEY (ID_PRODUTO)
);


ALTER TABLE TB_PRODUTO ADD CONSTRAINT tb_categoria_tb_produto_fk
FOREIGN KEY (ID_CATEGORIA)
REFERENCES TB_CATEGORIA (ID_CATEGORIA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
